name: Code Quality

on:
  pull_request:
    branches: [ 'main', 'dev' ]
    types:
      - opened
      - synchronize
  push:
    branches: [ 'dev' ]
  workflow_dispatch:
    if: github.actor != 'dependabot[bot]'

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0

    outputs:
      result: "success"
