name: Generate index.txt

on:
  workflow_run:
    workflows: ["Code Quality"]  # Name of the other workflow
    types:
      - completed

jobs:
  generate-index:
    # Check if the previous workflow was successful and it was on the dev branch
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: write
      pull-requests: write
      checks: read
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate index.txt
      run: |
        find . -name "Makefile" | grep -v "^./Makefile$" > index.txt

    - name: Create Pull Request using gh CLI
      run: |
        # Create a new branch for the changes
        git checkout -b update-index-txt-$(date +'%Y%m%d%H%M%S')

        # Commit the changes
        git add index.txt
        git commit -m "Automatically update index.txt" || echo "No changes to commit"

        # Push the new branch
        git push origin update-index-txt-$(date +'%Y%m%d%H%M%S')

        # Use gh CLI to create the PR
        gh pr create --base dev --head update-index-txt-$(date +'%Y%m%d%H%M%S') --title "Automatically update index.txt" --body "This PR updates the index.txt file." --repo ${{ github.repository }}
