name: Generate index.txt

on:
  workflow_run:
    workflows: ["Code Quality"]  # Name of the other workflow
    types:
      - completed

jobs:
  generate-index:
    # Check if the previous workflow was successful and it was on the dev branch
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'dev'
    permissions:
      contents: write
      checks: read
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate index.txt
      run: |
        find . -name "Makefile" | grep -v "^./Makefile$" > index.txt

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.txt
        git commit -m "Automatically update index.txt" || echo "No changes to commit"
        git push
