name: Generate index.txt

on:
  push:
    branches:
      - dev

jobs:
  generate-index:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate index.txt
      run: |
        find . -name "Makefile" | grep -v "^./Makefile$" > index.txt

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.txt
        git commit -m "Automatically update index.txt" || echo "No changes to commit"
        git push
